export const jobData = [
    {
      title: "Software Engineer",
      company: "Google",
      status: "Registered",
      location: "Bangalore, India",
      salary: "₹12-18 LPA",
      endDate: "Dec 31, 2023",
      driveType: "On Campus",
      registrationStatus: "Open",
      jobLink: "https://google.com/careers",
    },
    {
      title: "Frontend Developer",
      company: "Microsoft",
      status: "Open",
      location: "Hyderabad, India",
      salary: "₹10-15 LPA",
      endDate: "Jan 15, 2024",
      driveType: "Off Campus",
      registrationStatus: "Open",
      jobLink: "https://microsoft.com/careers",
    },
    {
      title: "Data Scientist",
      company: "Amazon",
      status: "Open",
      location: "Chennai, India",
      salary: "₹14-20 LPA",
      endDate: "Jan 20, 2024",
      driveType: "On Campus",
      registrationStatus: "Open",
      jobLink: "https://amazon.com/careers",
    },
    {
      title: "Backend Engineer",
      company: "Adobe",
      status: "Open",
      location: "Noida, India",
      salary: "₹11-16 LPA",
      endDate: "Jan 25, 2024",
      driveType: "On Campus",
      registrationStatus: "Open",
      jobLink: "https://adobe.com/careers",
    },
    {
      title: "Full Stack Developer",
      company: "Flipkart",
      status: "Open",
      location: "Bangalore, India",
      salary: "₹12-17 LPA",
      endDate: "Jan 30, 2024",
      driveType: "Off Campus",
      registrationStatus: "Open",
      jobLink: "https://flipkart.com/careers",
    },
    {
      title: "DevOps Engineer",
      company: "Oracle",
      status: "Open",
      location: "Mumbai, India",
      salary: "₹13-18 LPA",
      endDate: "Feb 5, 2024",
      driveType: "On Campus",
      registrationStatus: "Open",
      jobLink: "https://oracle.com/careers",
    },
    {
      title: "Cloud Engineer",
      company: "IBM",
      status: "Open",
      location: "Pune, India",
      salary: "₹11-16 LPA",
      endDate: "Feb 10, 2024",
      driveType: "On Campus",
      registrationStatus: "Open",
      jobLink: "https://ibm.com/careers",
    },
    {
      title: "ML Engineer",
      company: "Intel",
      status: "Open",
      location: "Bangalore, India",
      salary: "₹15-20 LPA",
      endDate: "Feb 15, 2024",
      driveType: "Off Campus",
      registrationStatus: "Open",
      jobLink: "https://intel.com/careers",
    },
    {
      title: "Systems Engineer",
      company: "Infosys",
      status: "Open",
      location: "Mysore, India",
      salary: "₹8-12 LPA",
      endDate: "Feb 20, 2024",
      driveType: "On Campus",
      registrationStatus: "Open",
      jobLink: "https://infosys.com/careers",
    },
    {
      title: "Product Engineer",
      company: "Walmart",
      status: "Open",
      location: "Bangalore, India",
      salary: "₹12-17 LPA",
      endDate: "Feb 25, 2024",
      driveType: "On Campus",
      registrationStatus: "Open",
      jobLink: "https://walmart.com/careers",
    }
  ]